const SET_OPENED_AUTHOR_ID = 'SET_OPENED_AUTHOR_ID';
const SET_FILTER_AUTHOR_TEXT = 'SET_FILTER_AUTHOR_TEXT';
const SET_FILTER_AUTHOR_SORT = 'SET_FILTER_AUTHOR_SORT';
const SET_FILTER_AUTHOR_STATUS = 'SET_FILTER_AUTHOR_STATUS';

const BOOKS_REQUEST = '@@books/BOOKS_REQUEST';
const BOOKS_SUCCESS = '@@books/BOOKS_SUCCESS';
const BOOKS_FAILURE = '@@books/BOOKS_FAILURE';

const FAVORITES_REQUEST = '@@bookshelves/FAVORITES_REQUEST';
const FAVORITES_SUCCESS = '@@bookshelves/FAVORITES_SUCCESS';
const FAVORITES_FAILURE = '@@bookshelves/FAVORITES_FAILURE';

const types = { 
    SET_OPENED_AUTHOR_ID,
    SET_FILTER_AUTHOR_TEXT,
    SET_FILTER_AUTHOR_SORT,
    SET_FILTER_AUTHOR_STATUS,
    BOOKS_REQUEST,
    BOOKS_SUCCESS,
    BOOKS_FAILURE,
    FAVORITES_REQUEST,
    FAVORITES_SUCCESS,
    FAVORITES_FAILURE
}

export default types